### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by jkytomak** [Azure/load-testing#128]
**Describe the bug**
We a triggering Azure load test from github and have not made any changes to workflows in long time.
They both  (2 different workflows) stopped working yesterday. Previous succesfull run was a week ago.

We get this error from all runs:
```
Run azure/load-testing@v1
node:internal/modules/cjs/loader:1215
  throw err;
  ^

Error: Cannot find module '@actions/core'
Require stack:
- /home/runner/work/_actions/azure/load-testing/v1/lib/Utils/CoreUtils.js
- /home/runner/work/_actions/azure/load-testing/v1/lib/main.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1212:15)
    at Module._load (node:internal/modules/cjs/loader:1043:27)
    at Module.require (node:internal/modules/cjs/loader:1298:19)
    at require (node:internal/modules/helpers:182:18)
    at Object.<anonymous> (/home/runner/work/_actions/azure/load-testing/v1/lib/Utils/CoreUtils.js:27:27)
    at Module._compile (node:internal/modules/cjs/loader:1529:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1613:10)
    at Module.load (node:internal/modules/cjs/loader:1275:32)
    at Module._load (node:internal/modules/cjs/loader:1096:12)
    at Module.require (node:internal/modules/cjs/loader:1298:19) ***
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/work/_actions/azure/load-testing/v1/lib/Utils/CoreUtils.js',
    '/home/runner/work/_actions/azure/load-testing/v1/lib/main.js'
  ]
```
***

Node.js v20.19.0

**Additional context**
Dev load test workflow:

```
on:
  workflow_dispatch:
  release:
    types: [prereleased]

name: Dev load tests

jobs:
  load-tests:
    name: 'Azure load test run'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to Azure
        uses: azure/login@v1
        continue-on-error: false
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: 'Azure Load Testing'
        uses: azure/load-testing@v1
        with:
          # https://github.com/Azure/load-testing?tab=readme-ov-file#azure-load-testing-action
          loadtestConfigFile: 'test/load/jmeter_azure_dev.yaml'
          loadtestResource: 'Load-testing-North-Europe'
          loadTestRunName: ${{ github.event.release.tag_name }}
          resourceGroup: 'load-testing'
```
