### ISSUE TITLE
[Feature Request] Parametrize the test run name

### ISSUE THREAD

**Issue by tonybaloney** [Azure/load-testing#42]
When executing the action, it would be useful to set the name of the test run in GitHub Actions (e.g. to the commit hash or branch) instead of the YAML file.

```yaml
     - name: 'Azure Load Testing'
        uses: azure/load-testing
        with:
          name: "${{ github.ref_name }} - ${{ github.run_number }} - ${{ github.sha }}"
          loadTestConfigFile: 'loadtest/smoketest.yaml'
          loadTestResource: ${{ env.AZURE_LOAD_TEST_NAME }}
          resourceGroup: ${{ env.AZURE_RESOURCE_GROUP_NAME }}
```
