### ISSUE TITLE
[BUG] Error 405 in test creation  with v1.1.12 action release

### ISSUE THREAD

**Issue by JoseAlvaradoCevallos** [Azure/load-testing#47]
I ran the GitHub action with the following input:
```yml
      - name: "Azure Load Testing"
        uses: azure/load-testing@v1
        with:
          loadTestConfigFile: "./test/performance/azure-load-testing/launch-configs/capacity/capacity-laliga.yml"
          loadTestResource: "LaLiga-Replication"
          resourceGroup: "baikal-${{ github.event.inputs.STATE `}}-state-rg"
```

This uses the action version v1.1.12 and returns: 
`Unable to fetch the response. Please re-run or contact support if the issue persists. Status code: 405`

When I run the previous version everything works as expected:
```yml
      - name: "Azure Load Testing"
        uses: azure/load-testing@v1.1.11
        with:
          loadTestConfigFile: "./test/performance/azure-load-testing/launch-configs/capacity/capacity-laliga.yml"
          loadTestResource: "LaLiga-Replication"
          resourceGroup: "baikal-${{ github.event.inputs.STATE `}}-state-rg"
```
