### ISSUE TITLE
[BUG] Load test fails on Windows runner

### ISSUE THREAD

**Issue by jcantosz** [Azure/load-testing#62]
**Describe the bug**
Load test cannot find the JMX file referenced by my config.yml on Windows runners. Works as expected on Linux runners. On Windows it fails with the message: `Error: File not found loadtest\quick_test.jmx`. 

I need to use Windows for my self-hosted runners, so I would like this to work on Windows.

**To Reproduce**
1. Create a load-test actions workflow
2. Set the `runs-on:` to `windows-2019` 
3. Run the worklfow
4. See error `Error: File not found loadtest\quick_test.jmx`

```yaml
name: Azure Load Test

on:
  workflow_dispatch:

permissions:
  id-token: write # This is required for requesting the JWT

jobs:
  # This job runs successfully
  deploy-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZ_CLIENT_ID }}
          tenant-id: ${{ secrets.AZ_TENANT_ID }}
          subscription-id: ${{ secrets.AZ_SUBSCRIPTION_ID }}
      - name: 'Azure Load Testing'
        uses: azure/load-testing@v1
        with:
          loadTestConfigFile: 'loadtest/config.yaml'
          loadTestResource: 'jcantosz-load-test'
          resourceGroup: 'jcantosz'

  # This job fails
  deploy-windows:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZ_CLIENT_ID }}
          tenant-id: ${{ secrets.AZ_TENANT_ID }}
          subscription-id: ${{ secrets.AZ_SUBSCRIPTION_ID }}
      - name: 'Azure Load Testing'
        uses: azure/load-testing@v1
        with:
          loadTestConfigFile: 'loadtest/config.yaml'
          loadTestResource: 'jcantosz-load-test'
          resourceGroup: 'jcantosz'
```

**Expected behavior**
I expect the load test to run on Windows the same way it does on Linux

**Screenshots**
Running load tests from Windows
<img width="1166" alt="Screenshot 2023-07-19 at 2 24 51 PM" src="https://github.com/Azure/load-testing/assets/22500761/06acae3b-a43d-4785-a197-1268b0526b03">

Running same load test from Linux
<img width="1157" alt="Screenshot 2023-07-19 at 2 26 41 PM" src="https://github.com/Azure/load-testing/assets/22500761/d36da1bb-f795-4012-97df-a287ed57c337">

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 2019

**Additional context**
Test config and jmx can be found [here](https://github.com/jcantosz-test-org/aspnetcore-sample/tree/main/loadtest)
Workflow for testing can be found [here](https://github.com/jcantosz-test-org/aspnetcore-sample/blob/main/.github/workflows/az-loadtest.yml)
